version: '3.8'

services:
  # 1. Backend (Go)
  backend:
    build: ./backend
    container_name: lica_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=host=postgres user=postgres password=postgres_password_secret dbname=lica_db port=5432 sslmode=disable TimeZone=Asia/Ho_Chi_Minh

  # 2. Frontend (Next.js - Khách)
  frontend:
    build: ./frontend
    container_name: lica_web
    restart: always
    ports:
      - "3000:3000"

  # 3. Admin (Next.js - Quản trị)
  admin:
    build: ./admin
    container_name: lica_admin
    restart: always
    ports:
      - "3001:3000"

  # 4. Database (Postgres) - Nếu muốn chạy DB chung
  postgres:
    image: postgres:15
    container_name: lica_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password_secret
      POSTGRES_DB: lica_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
